"""add minimum quantity to products

Revision ID: 75c6d697b43a
Revises:
Create Date: 2026-08-20 04:05:01.659033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c6d697b43a'
down_revision: Union[str, Sequence[str], None] = "1a7cf4bb3d10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column(
            'minimum_quantity',
            sa.Integer(),
            server_default='3',
            nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'minimum_quantity')
    # ### end Alembic commands ###
